version: "3.7"

services: 
  back:
    container_name: nestjs
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - back-data:/usr/src/app

  # db:
  #   container_name: libsql_server
  #   image: "ghcr.io/libsql/sqld:v0.21.9"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - back-data:/var/lib/sqld

volumes:
  back-data:
    name: back-data
    
